---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: praetorium
spec:
  rules:
  - host: praetorium.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: praetorium
            port:
              number: 80
