---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: praetorium
spec:
  selector:
    matchLabels:
      app: praetorium
  template:
    metadata:
      labels:
        app: praetorium
    spec:
      serviceAccountName: praetorium-dev
      securityContext:
        fsGroup: 1000
      containers:
        - name: praetorium
          image: shokohsc/praetorium
          command:
            - npm
          args:
            - run
            - skaffold
          env:
            - name: NODE_ENV
              value: development
          ports:
            - name: http
              containerPort: 5005
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
