---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: praetorium
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    praetorium.pawelmalak/name: praetorium
    praetorium.pawelmalak/url: dev.praetorium.shokohsc.home
    praetorium.pawelmalak/type: app
    praetorium.pawelmalak/icon: fire
spec:
  rules:
  - host: dev.praetorium.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: praetorium
            port:
              number: 80
  tls:
  - hosts:
    - dev.praetorium.shokohsc.home
    secretName: praetorium-cert
